
ktor {
  application {
    modules = [com.osucad.server.ApplicationKt.module]
  }

  deployment {
    port = 8080
  }
}

oauth {
  osu {
    redirectUrl = ${OSU_OAUTH_REDIRECT_URL}
    clientId = ${OSU_OAUTH_CLIENT_ID}
    clientSecret = ${OSU_OAUTH_CLIENT_SECRET}
  }
}

database {
  url = ${DATABASE_URL}
  driver = ${DATABASE_DRIVER}
  user = ${DATABASE_USER}
  password = ${DATABAE_PASSWORD}
}


documents {
  jwt {
    secret = ${DOCUMENT_JWT_SECRET}
    issuer = ${DOCUMENT_JWT_ISSUER}
    audience = ${DOCUMENT_JWT_AUDIENCE}
    realm = "documents"
    realm = ${?DOCUMENT_JWT_REALM}
  }
}