CREATE TABLE IF NOT EXISTS BEATMAPSETS
(
    ID         SERIAL PRIMARY KEY,
    CREATOR_ID INT                                 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ARTIST     VARCHAR(255)                        NOT NULL,
    TITLE      VARCHAR(255)                        NOT NULL,
    CONSTRAINT FK_BEATMAPSETS_CREATOR_ID__ID FOREIGN KEY (CREATOR_ID) REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS DOCUMENTS
(
    ID SERIAL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS BEATMAPS
(
    ID                  SERIAL PRIMARY KEY,
    BEATMAPSET_ID       INT                                 NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DIFFICULTY_OWNER_ID INT                                 NULL,
    ARTIST              VARCHAR(255)                        NOT NULL,
    TITLE               VARCHAR(255)                        NOT NULL,
    DIFFICULTY_NAME     VARCHAR(255)                        NOT NULL,
    DOCUMENT_ID         INT                                 NOT NULL,
    CONSTRAINT FK_BEATMAPS_BEATMAPSET_ID__ID FOREIGN KEY (BEATMAPSET_ID) REFERENCES BEATMAPSETS (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_BEATMAPS_DIFFICULTY_OWNER_ID__ID FOREIGN KEY (DIFFICULTY_OWNER_ID) REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_BEATMAPS_DOCUMENT_ID__ID FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS BLOBS
(
    ID     uuid PRIMARY KEY,
    "size" INT NOT NULL
);
CREATE TABLE IF NOT EXISTS DOCUMENT_SNAPSHOTS
(
    DOCUMENT_ID     INT,
    SEQUENCE_NUMBER BIGINT,
    SUMMARY_BLOB_ID uuid NOT NULL,
    CONSTRAINT pk_document_snapshots PRIMARY KEY (DOCUMENT_ID, SEQUENCE_NUMBER),
    CONSTRAINT FK_DOCUMENT_SNAPSHOTS_DOCUMENT_ID__ID FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_DOCUMENT_SNAPSHOTS_SUMMARY_BLOB_ID__ID FOREIGN KEY (SUMMARY_BLOB_ID) REFERENCES BLOBS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS DOCUMENT_BLOB_USAGES
(
    DOCUMENT_ID INT,
    BLOB_ID     uuid,
    CONSTRAINT pk_document_blob_usages PRIMARY KEY (DOCUMENT_ID, BLOB_ID),
    CONSTRAINT FK_DOCUMENT_BLOB_USAGES_DOCUMENT_ID__ID FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_DOCUMENT_BLOB_USAGES_BLOB_ID__ID FOREIGN KEY (BLOB_ID) REFERENCES BLOBS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
