CREATE TABLE IF NOT EXISTS BEATMAPSETS
(
    ID         SERIAL PRIMARY KEY,
    CREATOR_ID INT                                 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ARTIST     VARCHAR(255)                        NOT NULL,
    TITLE      VARCHAR(255)                        NOT NULL,
    CONSTRAINT FK_BEATMAPSETS_CREATOR_ID__ID FOREIGN KEY (CREATOR_ID) REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS BEATMAPS
(
    ID                  SERIAL PRIMARY KEY,
    BEATMAPSET_ID       INT                                 NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DIFFICULTY_OWNER_ID INT                                 NULL,
    ARTIST              VARCHAR(255)                        NOT NULL,
    TITLE               VARCHAR(255)                        NOT NULL,
    DIFFICULTY_NAME     VARCHAR(255)                        NOT NULL,
    CONSTRAINT FK_BEATMAPS_BEATMAPSET_ID__ID FOREIGN KEY (BEATMAPSET_ID) REFERENCES BEATMAPSETS (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_BEATMAPS_DIFFICULTY_OWNER_ID__ID FOREIGN KEY (DIFFICULTY_OWNER_ID) REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
